/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoSO2;


/**
 *
 * @author frand
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconRM = new javax.swing.JPanel();
        RMIcon = new javax.swing.JLabel();
        IconTLOU = new javax.swing.JPanel();
        TLOUIcon = new javax.swing.JLabel();
        Cola1TLOU = new javax.swing.JScrollPane();
        Prioridad1 = new javax.swing.JTextArea();
        Cola2TLOU = new javax.swing.JScrollPane();
        Prioridad2 = new javax.swing.JTextArea();
        Cola3TLOU = new javax.swing.JScrollPane();
        Prioridad3 = new javax.swing.JTextArea();
        jScrollPaneRefuerzos = new javax.swing.JScrollPane();
        Refuerzos = new javax.swing.JTextArea();
        HalfTime = new javax.swing.JButton();
        idRM = new javax.swing.JTextField();
        idTLOU = new javax.swing.JTextField();
        nombreRM = new javax.swing.JTextField();
        nombreTLOU = new javax.swing.JTextField();
        RMListo = new javax.swing.JTextField();
        TLOUListo = new javax.swing.JTextField();
        poderRM = new javax.swing.JTextField();
        poderTLOU = new javax.swing.JTextField();
        Prioridad1Rm1 = new javax.swing.JLabel();
        Prioridad1TLOU = new javax.swing.JLabel();
        Prioridad2TLOU = new javax.swing.JLabel();
        Prioridad3TLOU = new javax.swing.JLabel();
        IDTLOU = new javax.swing.JLabel();
        NameTLOU = new javax.swing.JLabel();
        PoderTLOU = new javax.swing.JLabel();
        Prioridad1Rm = new javax.swing.JLabel();
        Prioridad2TLOU1 = new javax.swing.JLabel();
        Prioridad3TLOU1 = new javax.swing.JLabel();
        Cola3RM = new javax.swing.JScrollPane();
        Prioridad6 = new javax.swing.JTextArea();
        Cola2RM = new javax.swing.JScrollPane();
        Prioridad5 = new javax.swing.JTextArea();
        Cola1RM = new javax.swing.JScrollPane();
        Prioridad4 = new javax.swing.JTextArea();
        IDTLOU1 = new javax.swing.JLabel();
        NameTLOU1 = new javax.swing.JLabel();
        PoderTLOU1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RMIcon.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout IconRMLayout = new javax.swing.GroupLayout(IconRM);
        IconRM.setLayout(IconRMLayout);
        IconRMLayout.setHorizontalGroup(
            IconRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RMIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IconRMLayout.setVerticalGroup(
            IconRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RMIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel1.add(IconRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 190));

        TLOUIcon.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout IconTLOULayout = new javax.swing.GroupLayout(IconTLOU);
        IconTLOU.setLayout(IconTLOULayout);
        IconTLOULayout.setHorizontalGroup(
            IconTLOULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TLOUIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IconTLOULayout.setVerticalGroup(
            IconTLOULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TLOUIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel1.add(IconTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 190, 190));

        Prioridad1.setEditable(false);
        Prioridad1.setColumns(20);
        Prioridad1.setRows(5);
        Cola1TLOU.setViewportView(Prioridad1);

        jPanel1.add(Cola1TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 290, 100));

        Prioridad2.setEditable(false);
        Prioridad2.setColumns(20);
        Prioridad2.setRows(5);
        Cola2TLOU.setViewportView(Prioridad2);

        jPanel1.add(Cola2TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 290, 100));

        Prioridad3.setEditable(false);
        Prioridad3.setColumns(20);
        Prioridad3.setRows(5);
        Cola3TLOU.setViewportView(Prioridad3);

        jPanel1.add(Cola3TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 300, 100));

        Refuerzos.setEditable(false);
        Refuerzos.setColumns(20);
        Refuerzos.setRows(5);
        jScrollPaneRefuerzos.setViewportView(Refuerzos);

        jPanel1.add(jScrollPaneRefuerzos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 340, 170));

        HalfTime.setText("Half-Time");
        HalfTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HalfTimeActionPerformed(evt);
            }
        });
        jPanel1.add(HalfTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        idRM.setEditable(false);
        idRM.setRequestFocusEnabled(false);
        idRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRMActionPerformed(evt);
            }
        });
        jPanel1.add(idRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 30, -1));

        idTLOU.setEditable(false);
        idTLOU.setRequestFocusEnabled(false);
        idTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(idTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 30, -1));

        nombreRM.setEditable(false);
        jPanel1.add(nombreRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 150, -1));

        nombreTLOU.setEditable(false);
        jPanel1.add(nombreTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 150, -1));

        RMListo.setEditable(false);
        RMListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RMListoActionPerformed(evt);
            }
        });
        jPanel1.add(RMListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 30, -1));

        TLOUListo.setEditable(false);
        jPanel1.add(TLOUListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 30, -1));

        poderRM.setEditable(false);
        jPanel1.add(poderRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 30, -1));

        poderTLOU.setEditable(false);
        jPanel1.add(poderTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 30, -1));

        Prioridad1Rm1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Prioridad1Rm1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad1Rm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Prioridad1Rm1.setText("PUNTAJE");
        jPanel1.add(Prioridad1Rm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 100, -1));

        Prioridad1TLOU.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad1TLOU.setText("Prioridad 1");
        jPanel1.add(Prioridad1TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        Prioridad2TLOU.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad2TLOU.setText("Prioridad 2");
        jPanel1.add(Prioridad2TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        Prioridad3TLOU.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad3TLOU.setText("Prioridad 3");
        jPanel1.add(Prioridad3TLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, -1));

        IDTLOU.setForeground(new java.awt.Color(255, 255, 255));
        IDTLOU.setText("ID");
        jPanel1.add(IDTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        NameTLOU.setForeground(new java.awt.Color(255, 255, 255));
        NameTLOU.setText("Nombre");
        jPanel1.add(NameTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        PoderTLOU.setForeground(new java.awt.Color(255, 255, 255));
        PoderTLOU.setText("Poder ");
        jPanel1.add(PoderTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        Prioridad1Rm.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad1Rm.setText("Prioridad 1");
        jPanel1.add(Prioridad1Rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, -1));

        Prioridad2TLOU1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad2TLOU1.setText("Prioridad 2");
        jPanel1.add(Prioridad2TLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 590, -1, -1));

        Prioridad3TLOU1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad3TLOU1.setText("Prioridad 3");
        jPanel1.add(Prioridad3TLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        Prioridad6.setEditable(false);
        Prioridad6.setColumns(20);
        Prioridad6.setRows(5);
        Cola3RM.setViewportView(Prioridad6);

        jPanel1.add(Cola3RM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 280, 90));

        Prioridad5.setEditable(false);
        Prioridad5.setColumns(20);
        Prioridad5.setRows(5);
        Cola2RM.setViewportView(Prioridad5);

        jPanel1.add(Cola2RM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 260, 90));

        Prioridad4.setEditable(false);
        Prioridad4.setColumns(20);
        Prioridad4.setRows(5);
        Cola1RM.setViewportView(Prioridad4);

        jPanel1.add(Cola1RM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 290, 100));

        IDTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        IDTLOU1.setText("ID");
        jPanel1.add(IDTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 100, -1, -1));

        NameTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        NameTLOU1.setText("Nombre");
        jPanel1.add(NameTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, -1, -1));

        PoderTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        PoderTLOU1.setText("Poder ");
        jPanel1.add(PoderTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 220, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoSO2/Imagenes/Proyecto SO HboMax Interface (1366 × 768 px) (3).png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HalfTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HalfTimeActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_HalfTimeActionPerformed

    private void idTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTLOUActionPerformed

    private void idRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRMActionPerformed

    private void RMListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RMListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RMListoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Cola1RM;
    private javax.swing.JScrollPane Cola1TLOU;
    private javax.swing.JScrollPane Cola2RM;
    private javax.swing.JScrollPane Cola2TLOU;
    private javax.swing.JScrollPane Cola3RM;
    private javax.swing.JScrollPane Cola3TLOU;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton HalfTime;
    private javax.swing.JLabel IDTLOU;
    private javax.swing.JLabel IDTLOU1;
    public javax.swing.JPanel IconRM;
    public javax.swing.JPanel IconTLOU;
    private javax.swing.JLabel NameTLOU;
    private javax.swing.JLabel NameTLOU1;
    private javax.swing.JLabel PoderTLOU;
    private javax.swing.JLabel PoderTLOU1;
    public static javax.swing.JTextArea Prioridad1;
    private javax.swing.JLabel Prioridad1Rm;
    private javax.swing.JLabel Prioridad1Rm1;
    private javax.swing.JLabel Prioridad1TLOU;
    public static javax.swing.JTextArea Prioridad2;
    private javax.swing.JLabel Prioridad2TLOU;
    private javax.swing.JLabel Prioridad2TLOU1;
    public static javax.swing.JTextArea Prioridad3;
    private javax.swing.JLabel Prioridad3TLOU;
    private javax.swing.JLabel Prioridad3TLOU1;
    public static javax.swing.JTextArea Prioridad4;
    public static javax.swing.JTextArea Prioridad5;
    public static javax.swing.JTextArea Prioridad6;
    public static javax.swing.JLabel RMIcon;
    public static javax.swing.JTextField RMListo;
    public static javax.swing.JTextArea Refuerzos;
    public static javax.swing.JLabel TLOUIcon;
    public static javax.swing.JTextField TLOUListo;
    public static javax.swing.JTextField idRM;
    public static javax.swing.JTextField idTLOU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneRefuerzos;
    public static javax.swing.JTextField nombreRM;
    public static javax.swing.JTextField nombreTLOU;
    public static javax.swing.JTextField poderRM;
    public static javax.swing.JTextField poderTLOU;
    // End of variables declaration//GEN-END:variables
}
